import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "التصلب اللويحي",
  description: "Generated by MTN-Development",
};

const pnu = localFont({
  src: "./fonts/ArbFONTS-PNU-Regular.ttf",
  variable: "--font-pnu",
  weight: "100 900",
});

const expo = localFont({
  src: "./fonts/ArbFONTS-ExpoArabic-Book.ttf",
  variable: "--font-expo",
  weight: "100 900",
});

const tajawal = localFont({
  src: "./fonts/Tajawal-Regular.ttf",
  variable: "--font-tajawal",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pnu.variable} ${expo.variable} ${tajawal.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
